"""phase1_create_all_tables

Revision ID: 9aa53f78df44
Revises: 
Create Date: 2026-03-21 20:27:09.090563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa53f78df44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('brand_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('brands',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('brand_type', sa.Text(), nullable=False),
    sa.Column('google_place_id', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('foody_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brands_is_active', 'brands', ['is_active'], unique=False)
    op.create_index('idx_brands_user_id', 'brands', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('change_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('hours_snapshots',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('hours_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('popular_times', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hours_snapshots_brand_date', 'hours_snapshots', ['brand_id', sa.text('snapshot_date DESC')], unique=False)
    op.create_table('menu_snapshots',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_snapshots_brand_date', 'menu_snapshots', ['brand_id', sa.text('snapshot_date DESC')], unique=False)
    op.create_table('social_snapshots',
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_posts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_snapshots_brand_platform', 'social_snapshots', ['brand_id', 'platform', sa.text('snapshot_date DESC')], unique=False)
    op.create_table('brand_changes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('field_changed', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('old_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('new_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_snapshot_id'], ['menu_snapshots.id'], ),
    sa.ForeignKeyConstraint(['old_snapshot_id'], ['menu_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_changes_brand_id', 'brand_changes', ['brand_id'], unique=False)
    op.create_index('idx_brand_changes_detected_at', 'brand_changes', [sa.text('detected_at DESC')], unique=False)
    op.create_index('idx_brand_changes_notified_at', 'brand_changes', ['notified_at'], unique=False, postgresql_where=sa.text('notified_at IS NULL'))
    op.create_index('idx_brand_changes_severity', 'brand_changes', ['severity'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('detected_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['menu_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_menu_items_brand_id', 'menu_items', ['brand_id'], unique=False)
    op.create_index('idx_menu_items_snapshot_id', 'menu_items', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_menu_items_snapshot_id', table_name='menu_items')
    op.drop_index('idx_menu_items_brand_id', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('idx_brand_changes_severity', table_name='brand_changes')
    op.drop_index('idx_brand_changes_notified_at', table_name='brand_changes', postgresql_where=sa.text('notified_at IS NULL'))
    op.drop_index('idx_brand_changes_detected_at', table_name='brand_changes')
    op.drop_index('idx_brand_changes_brand_id', table_name='brand_changes')
    op.drop_table('brand_changes')
    op.drop_index('idx_social_snapshots_brand_platform', table_name='social_snapshots')
    op.drop_table('social_snapshots')
    op.drop_index('idx_menu_snapshots_brand_date', table_name='menu_snapshots')
    op.drop_table('menu_snapshots')
    op.drop_index('idx_hours_snapshots_brand_date', table_name='hours_snapshots')
    op.drop_table('hours_snapshots')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('notifications')
    op.drop_index('idx_brands_user_id', table_name='brands')
    op.drop_index('idx_brands_is_active', table_name='brands')
    op.drop_table('brands')
    op.drop_table('users')
    # ### end Alembic commands ###
