"""add social media columns to brands

Revision ID: e28bcbafc607
Revises: 9aa53f78df44
Create Date: 2026-03-22 13:41:39.037130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28bcbafc607'
down_revision: Union[str, None] = '9aa53f78df44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('tiktok_username', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('instagram_username', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('facebook_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'facebook_url')
    op.drop_column('brands', 'instagram_username')
    op.drop_column('brands', 'tiktok_username')
    # ### end Alembic commands ###
